name: reverse_IP_server CI
on: 
  push: 
    branches: [ "main" ]

  
jobs:
  reverse_IP_server:
   
  
    name: Build Docker Image
    runs-on: ubuntu-latest 
    environment: dev

    steps:  
        - name: Checkout
          uses: actions/checkout@v2  

        - name: Set short git commit SHA
          id: commit
          uses: prompt/actions-commit-hash@v2  
          
        - name: Setup AWS ECR Details
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-2


        - name: Login to Amazon ECR
          id: login-pf-aws-ecr
          uses: aws-actions/amazon-ecr-login@v1         

        - name: Build, tag, and push image to Amazon ECR
          env:
            ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO}}        
#           IMAGE_TAG: ${{ steps.commit.outputs.short }}
            IMAGE_TAG: latest
          run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG  .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


      